spring:
  application:
    name: actuator-example
    
info:
  app:
    name: $(spring.application.name)    
    author: Java Thas
    
  build:
    artifactId: '@project.artifact@'
    groupId: '@project.groupId@'
    version: '@project.version@'
    
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
        
  endpoint:
    health:     
      show-details: always
    shutdown:
      enabled: true  
      
  info:
    env:
      enabled: true
    java:
      enabled: true       
            




      